# Generated by Django 3.0.8 on 2021-08-11 19:15
from django.core.management import call_command
from django.db import migrations


def load_settings(apps, schema_editor):
    call_command('loaddata', 'url_shortener/migrations/fixtures/settings.json')


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_settings, migrations.RunPython.noop),
    ]
